// pokemon-battles/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { Auth } from '@angular/fire/auth'


@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: [
    './home.component.css',
    '../app.component.css'
  ]
})
export class HomeComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }
  
}

<div id="welcome" class='full-screen'>
    <div id="intro">
        <h3>Welcome to</h3>
        <img src='../../assets/items/Pokemon3.png' alt="" />
        <h2>Battles</h2>
    </div>
    <img src='../../assets/people/ashketchum.png' alt="pokeball animation" class='m-auto'/>
    <div id="login-button">
        <a href='./create'>
            <button>Create Account</button><br/>
        </a>
        <small>Already have an account? <a href='./login' id="login">Login</a></small>
    </div>
</div>

// pokemon-battles-react/src/pages/home/Home.js
import React from 'react';
import './Home.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import pokemon from '../../img/items/Pokemon3.png';
import pokeball from '../../img/items/pokemonball.png';
import ash from '../../img/people/ashketchum.png';
import { Link } from 'react-router-dom';


const Home = () => {
    return ( 
        <div id="welcome" className='full-screen'>
            <div id="intro">
                <h3>Welcome to</h3>
                <img src={pokemon} alt="" />
                <h2>Battles</h2>
            </div>
            <img src={ash} alt="pokeball animation" className='m-auto'/>
            <div id="login-button">
                <Link to='./create'>
                    <button onClick={'./create'}>Create Account</button><br/>
                </Link>
                <small>Already have an account? <Link to='./login' id="login">Login</Link></small>
            </div>
        </div>    
    );
}
 
export default Home;
